/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const @testing-library/react: typeof import('#imports')['@testing-library/react']
  const Activity: typeof import('react').Activity
  const Fragment: typeof import('react').Fragment
  const Suspense: typeof import('react').Suspense
  const afterAll: typeof import('vitest').afterAll
  const afterEach: typeof import('vitest').afterEach
  const assert: typeof import('vitest').assert
  const beforeAll: typeof import('vitest').beforeAll
  const beforeEach: typeof import('vitest').beforeEach
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const chai: typeof import('vitest').chai
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const describe: typeof import('vitest').describe
  const expect: typeof import('vitest').expect
  const forwardRef: typeof import('react').forwardRef
  const it: typeof import('vitest').it
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const startTransition: typeof import('react').startTransition
  const suite: typeof import('vitest').suite
  const test: typeof import('vitest').test
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useMemo: typeof import('react').useMemo
  const useOptimistic: typeof import('react').useOptimistic
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
  const vi: typeof import('vitest').vi
  const vitest: typeof import('vitest').vitest
}
